version: '3'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PW: ${DB_USER_PW}
        DB_ROOT_PW: ${DB_ROOT_PW}
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: always
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    env_file:
    - .env
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always
  redis:
    build:
      context: .
      dockerfile: requirements/redis/Dockerfile
    container_name: redis
    networks:
      - inception
    restart: always
  vsftpd:
    build:
      context: .
      dockerfile: requirements/vsftpd/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    env_file:
      - .env
    container_name: vsftpd
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/
    networks:
     - inception
    restart: always
volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wildberries

  db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/masha

networks:
    inception:
        driver: bridge